 setenv MASKERDIR /home/cynthia/Local/masker
 setenv DESIGN_HOME /home/cynthia/Local/masker
 setenv MSIZE   512
 setenv DTHETA  9.0 
 setenv MASKLIB      $MASKERDIR/$MSIZE.mask
 setenv VMASK        $MASKERDIR/$MSIZE.vmask
 setenv VTRIANGLE    $MASKERDIR/$MSIZE.tri
 setenv MASKTEMPLATE $MASKERDIR/$MSIZE.sort
 setenv MASKDAT      $MASKERDIR/$MSIZE.dat
 setenv ATOMLIB      $MASKERDIR/atoms.lib
 setenv COUNTBITS    $MASKERDIR/cbits.bin
 setenv COLLARS      $MASKERDIR/collars$MSIZE.bin
 setenv SLOPES       $MASKERDIR/slopes$DTHETA.dat
 setenv FORCEFIELD   $MASKERDIR/gromacs_ff.prm
