 setenv MASKERDIR `pwd`
 setenv DESIGN_HOME `pwd`
 setenv MSIZE   1024
 setenv DTHETA   4.5
 setenv MASKLIB      $MASKERDIR/$MSIZE.mask
 setenv VMASK        $MASKERDIR/$MSIZE.vmask
 setenv VTRIANGLE    $MASKERDIR/$MSIZE.tri
 setenv MASKTEMPLATE $MASKERDIR/$MSIZE.sort
 setenv MASKDAT      $MASKERDIR/$MSIZE.dat
 setenv ATOMLIB      $MASKERDIR/atoms.lib
 setenv COUNTBITS    $MASKERDIR/cbits.bin
 setenv COLLARS      $MASKERDIR/collars$MSIZE.bin
 setenv SLOPES       $MASKERDIR/slopes$DTHETA.dat
 setenv FORCEFIELD   $MASKERDIR/gromacs_ff.prm
